<?php require('template/header.phtml') ?>
<div class="container-fluid about-container">
    <section>
        <!-- A carousal for slide show about me, utilized bootstrap auto play carousel -->
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <!-- First carousel slide -->
                <div class="carousel-item active" data-bs-interval="3000">
                    <!-- Note: data-bs-interval determine how long they slide will show and then next slide will come up-->
                    <img src="assets/about/carousel-1.png" alt="Carousel slide 1">
                    <!-- Carousel-caption class div is to transform content into center -->
                    <div class="carousel-caption">
                        <h1>HAI, IM SUJON</h1>
                        <h2>I'M A SOFTWARE DEVELOPER CURRENTLY ALSO PURSUING A CS DEGREE AT SALFORD</h2>

                        <div class="learn-more-link">
                            <a href="projects.php" class="custom-link">View Projects</a>
                        </div>
                        <!-- button to allow user to change the slide numbers -->
                        <div class="btn-group">
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="0"></button>
                            <!--Note:  data-bs-slide-to allows user to change the slide they want to see-->
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="1"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="2"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="3"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="4"></button>
                        </div>
                    </div>
                </div>
                <!-- Second slide -->
                <div class="carousel-item" data-bs-interval="3000">
                    <img src="assets/about/carousel-2.png" alt="slide 1">
                    <div class="carousel-caption">
                        <h1>LOVE DIGITAL</h1>
                        <h2>LOVE MAKING INTERACTIVE WEBSITES WITH A USER-FIRST APPROACH</h2>

                        <div class="learn-more-link">
                            <a href="projects.php" class="custom-link">View Projects</a>
                        </div>

                        <!-- button to allow user to change the slide numbers -->
                        <div class="btn-group">
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="0"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="1"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="2"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="3"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="4"></button>
                        </div>
                    </div>
                </div>
                <!-- Third slide -->
                <div class="carousel-item" data-bs-interval="3000">
                    <img src="assets/about/carousel-3.png" alt="slide 3">
                    <div class="carousel-caption">
                        <h1>INTERESTED?</h1>
                        <h2>IF YOU'VE GOT AN AMAZING IDEA THAT YOU WANT TO GIVE A DIGITAL PRESENCE, GET IN TOUCH
                        </h2>

                        <div class="learn-more-link">
                            <a href="projects.php" class="custom-link">View Projects</a>
                        </div>

                        <!-- button to allow user to change the slide numbers -->
                        <div class="btn-group"> <!-- Button group to-->
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="0"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="1"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="2"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="3"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="4"></button>
                        </div>
                    </div>
                </div>
                <!-- Fourth slide -->
                <div class="carousel-item" data-bs-interval="3000">
                    <img src="assets/about/carousel-4.png" alt="slide 4">
                    <div class="carousel-caption">
                        <h1>ARTISTIC</h1>
                        <h2>I BELIEVE ART SHOULD BE TAKEN INTO CONSIDERATION IN DIGITAL PRODUCTS, AS EVERYTHING IS
                            BECOMING DIGITAL; WHY NOT HAVE SOME ARTISTIC FLAVOUR IN OUR DIGITAL PRESENCE?</h2>

                        <div class="learn-more-link">
                            <a href="projects.php" class="custom-link">View Projects</a>
                        </div>

                        <!-- button to allow user to change the slide numbers -->
                        <div class="btn-group">
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="0"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="1"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="2"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="3"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="4"></button>
                        </div>
                    </div>
                </div>
                <!-- Fifth slide -->
                <div class="carousel-item" data-bs-interval="3000">
                    <img src="assets/about/carousel-5.png" alt="slide 5">
                    <div class="carousel-caption">
                        <h1>LOVE EXPERIMENTING</h1>
                        <h2>AS I SPEND MOST OF MY TIME CODING AND BUILDING, I LIKE TO EXPERIMENT AND HAVE FUN WITH
                            MY DEVELOPMENT CAREER</h2>

                        <div class="learn-more-link">
                            <a href="projects.php" class="custom-link">View Projects</a>
                        </div>

                        <!-- button to allow user to change the slide numbers -->
                        <div class="btn-group">
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="0"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="1"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="2"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="3"></button>
                            <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide-to="4"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


<div class="about-section-1-container">

    <div class="container">
        <section class="about-section-1">
            <div class="row">
                <div class="col-sm-12 col-md-6 profile-intro d-flex flex-column justify-content-center text-center">
                    <h1>About Me</h1>
                </div>
                <div class="col-sm-12 col-md-6  about-profile text-center">
                    <img src="assets/about/profile2.jpg" alt="profile">
                </div>
                <div class="col-md-12 about-me-para my-5">
                    <p>
                        Hello there! I’m passionate about software developement and also pursuing a BSc in Computer
                        Science at the University of Salford. I have a couple of years hands-on experience in web
                        development and right now I am exploring software security, REST APIs, AI and Data Mining.
                        Passionate about creating clean, user-friendly interfaces, learning new technologies,
                        and contributing to meaningful projects.I am leading a team of five peers in developing software
                        based on real client requirements for the Salford Agile Hack Camp.
                        I was a Team Leader at my previous employment, and currently working part-time as a team member.
                    </p>

                    <p>
                        Before starting university, I taught myself Bootstrap, JavaScript, CSS, HTML, Photoshop, and logo design — essentially everything needed for static front-end development.
                        I find great joy in creating interactive websites with a unique touch.
                        At present, I am working on a full-stack web project called <strong>Pet Watch</strong>, which involves database integration (MySQL), PHP for the back end, Google Maps API for location services, JavaScript for the user interface, and much more.
                    </p>

                    <p>
                        In addition to web development, I also have experience in Java software development.
                        For a university project, I am building a game in Java, and I recently completed a console based project call <strong>Sputnik Vehicle Hire System</strong>.
                        I intend to expand that project with a JavaFX GUI to create a cross-platform application.
                    </p>

                    <p>
                        I am looking for an industrial placement to gain hands-on experience and contribute in developing cutting edge solutions.
                        Feel free to email me if you’d like to hire me or collaborate.
                        Thank you for taking the time to read this!
                    </p>
                </div>
            </div>
        </section>
    </div>
</div>


<?php require('template/footer.phtml') ?>