<?php require('template/header.phtml') ?>
   <section>
    <!-- A carousal for slide show about me, utilized bootstrap auto play carousel -->
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <!-- First carousel slide -->
            <div class="carousel-item active" data-bs-interval="3000">
                <!-- Note: data-bs-interval determine how long they slide will show and then next slide will come up-->
                <img src="assets/carousel-1.png" alt="Carousel slide 1">
                <!-- Carousel-caption class div is to transform content into center -->
                <div class="carousel-caption">
                    <h1>HAI, IM SUJON</h1>
                    <h2>I'M A FRONT-END DEVELOPER CURRENTLY ALSO PURSUING A CS DEGREE AT SALFORD</h2>

                    <div class="learn-more-link">
                        <a href="interests.html" class="custom-link">LEARN MORE</a>
                    </div>
                    <!-- button to allow user to change the slide numbers -->
                    <div class="btn-group">
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="0"></button>
                        <!--Note:  data-bs-slide-to allows user to change the slide they want to see-->
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="1"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="2"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="3"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="4"></button>
                    </div>
                </div>
            </div>
            <!-- Second slide -->
            <div class="carousel-item" data-bs-interval="3000">
                <img src="assets/carousel-2.png" alt="slide 1">
                <div class="carousel-caption">
                    <h1>LOVE DIGITAL</h1>
                    <h2>LOVE MAKING INTERACTIVE WEBSITES WITH A USER-FIRST APPROACH</h2>

                    <div class="learn-more-link">
                        <a href="interests.html" class="custom-link">LEARN MORE</a>
                    </div>

                    <!-- button to allow user to change the slide numbers -->
                    <div class="btn-group">
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="0"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="1"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="2"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="3"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="4"></button>
                    </div>
                </div>
            </div>
            <!-- Third slide -->
            <div class="carousel-item" data-bs-interval="3000">
                <img src="assets/carousel-3.png" alt="slide 3">
                <div class="carousel-caption">
                    <h1>INTERESTED?</h1>
                    <h2>IF YOU'VE GOT AN AMAZING IDEA THAT YOU WANT TO GIVE A DIGITAL PRESENCE, GET IN TOUCH
                    </h2>

                    <div class="learn-more-link">
                        <a href="interests.html" class="custom-link">LEARN MORE</a>
                    </div>

                    <!-- button to allow user to change the slide numbers -->
                    <div class="btn-group"> <!-- Button group to-->
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="0"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="1"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="2"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="3"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="4"></button>
                    </div>
                </div>
            </div>
            <!-- Fourth slide -->
            <div class="carousel-item" data-bs-interval="3000">
                <img src="assets/carousel-4.png" alt="slide 4">
                <div class="carousel-caption">
                    <h1>ARTISTIC</h1>
                    <h2>I BELIEVE ART SHOULD BE TAKEN INTO CONSIDERATION IN DIGITAL PRODUCTS, AS EVERYTHING IS
                        BECOMING DIGITAL; WHY NOT HAVE SOME ARTISTIC FLAVOUR IN OUR DIGITAL PRESENCE?</h2>

                    <div class="learn-more-link">
                        <a href="interests.html" class="custom-link">LEARN MORE</a>
                    </div>

                    <!-- button to allow user to change the slide numbers -->
                    <div class="btn-group">
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="0"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="1"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="2"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="3"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="4"></button>
                    </div>
                </div>
            </div>
            <!-- Fifth slide -->
            <div class="carousel-item" data-bs-interval="3000">
                <img src="assets/carousel-5.png" alt="slide 5">
                <div class="carousel-caption">
                    <h1>LOVE EXPERIMENTING</h1>
                    <h2>AS I SPEND MOST OF MY TIME CODING AND BUILDING, I LIKE TO EXPERIMENT AND HAVE FUN WITH
                        MY DEVELOPMENT CAREER</h2>

                    <div class="learn-more-link">
                        <a href="interests.html" class="custom-link">LEARN MORE</a>
                    </div>

                    <!-- button to allow user to change the slide numbers -->
                    <div class="btn-group">
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="0"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="1"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="2"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="3"></button>
                        <button class="custom-btn" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide-to="4"></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>


    <section>
        <div class="row">
            <div class="col profile-intro">
                <h1>About Me</h1>
            </div>
            <div class="col profile">
                <img src="assets/profile-1.png" alt="profile">
            </div>
            <div class="col-md-12 about-me-para my-5">
                <p>
                    Hello, I'm Abdur Rahim Sujon,
                    but most people knows me simply as Sujon.
                    I can't explain why my first name isn't widely recognized,
                    that remained a mystery to me as well.
                    Right now, I am pursuing a BSc in Computer Science at the University of
                    Salford, and I'm nearing the end of my first year. Honestly, I'm pleased with my choice of
                    university
                    over others because I've found that my degree focuses more on practical applications of computer
                    science
                    rather than
                    theory. As someone who values tangible progress, I appreciate seeing the real-life implications of
                    what
                    I do in coding. Fortunately, I have already learned advanced CSS, HTML, and how to showcase my web
                    portfolio in my first
                    year. Additionally, for a university project,
                    I can select the website I want to create, which I find very flexible. I've also gained insights
                    into Human-Computer Interaction.
                    A computer scientist truly isn't complete without some Linux knowledge (just kidding), and I've
                    already covered that in my first year! I'm eager
                    to delve deeper into Linux during the summer break. Moreover,
                    I've developed a solid understanding of Java programming too.
                </p>
                <p>
                    Prior to commencing university, I taught myself Bootstrap, JavaScript, Photoshop, logo design, CSS,
                    and
                    HTML—essentially everything needed for front-end web development projects.
                    I find great joy in creating interactive websites with a unique flair. My immediate goal is to learn
                    PHP
                    as soon as possible to better understand the back end of websites.
                    Since I already have knowledge of SQL, it shouldn't be too difficult. However, if it proves
                    challenging,
                    I'm confident I will find it enjoyable.
                    I plan to work on two advanced web projects that incorporate back-end functionality in my summer
                    vacation.
                </p>
                <p>
                    Conversely, I also have experience in Java software development.
                    Recently, I worked on a project to create a vehicle hire reservation system.
                    I intend to expand that project and develop a cross-platform application.
                </p>
                <p>I appreciate you taking the time to read this! Feel free to email me if you'd like to chat.</p>
            </div>
        </div>
    </section>

<?php require('template/footer.phtml') ?>