<?php require('template/header.phtml') ?>

    <!-- Section 1 -->
    <section id="project-section-1">
        <div class="container custom-container gradient-border">

            <div class="row">

                <!-- Left: Image Carousel -->
                <div class="col-md-6 text-center">
                    <div class="position-relative project-image-div custom-img">
                        <img id="carousel-image"  class="img-fluid" src="assets/projects/project 1/image 1.png"
                             alt="Project image"/>
                    </div>

                    <div class="control-div">
                        <button class="arrow-btn"
                                onclick="prevImage()"><img src="assets/projects/project 1/arrow-left-circle.svg"/>
                        </button>
                        <button class="arrow-btn"
                                onclick="nextImage()"><img src="assets/projects/project 1/arrow-right-circle.svg"/>
                        </button>
                    </div>
                    <div id="carousel-dots" class="mt-2"></div>
                </div>

                <!-- Right: Project Info -->
                <div class="col-md-6 d-flex flex-column justify-content-between">
                    <div>
                        <h2 id="project-title" class="fw-bold">Emilia's Della Roma</h2>
                        <p id="project-desc" class="text-muted">
                        </p>
                        <p id="tech-stack" class="text-muted">
                        </p>
                        <a id="launch-link" href="https://example.com" target="_blank" class="btn btn-dark">Launch</a>
                    </div>
                    <div class="text-end">
                        <button class="btn btn-outline-secondary mt-3"  onclick="prevProject()">Previous Project</button>
                        <button class="btn btn-outline-secondary mt-3"  onclick="nextProject()">Next Project</button>
                    </div>
                </div>

            </div>

        </div>
    </section>

<?php require('template/footer.phtml') ?>