</main>


<div>
    <div class="container">
        <footer class="d-flex footer flex-wrap justify-content-between align-items-center ">
            <div class="col-md-4 d-flex align-items-center"><span class="mb-3 mb-md-0 rights">© 2025</span></div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li>
                    <a class="nav-link footer-icon" href="index.php" title="Home">
                        <img src="assets/home.png" alt="home">
                    </a>
                </li>
                <li>
                    <a class="nav-link footer-icon" href="about.php" title="About Me">
                        <img src="assets/about.png" alt="about">
                    </a>
                </li>
                <li>
                    <a class="nav-link footer-icon" href="index.php#section-2" title="My Skills">
                        <img src="assets/skills.png" alt="skills">
                    </a>
                </li>
                <li>
                    <a class="nav-link footer-icon" href="projects.php" title="View My Projects">
                        <img src="assets/work.png" alt="work">
                    </a>
                </li>
                <li>
                    <a class="nav-link footer-icon" href="mailto:abdur.sujon.dev@gmail.com" title="Email Me">
                        <img src="assets/email.png" alt="email">
                    </a>
                </li>
                <li>
                    <a class="nav-link footer-icon" href="https://www.linkedin.com/in/abdursujon/" title="View My LinkedIn">
                        <img src="assets/linkedin.png" alt="LinkedIn">
                    </a>
                </li>
                <li>
                    <a class="nav-link footer-icon" href="https://github.com/abdursujon" title="View My Github">
                        <img src="assets/github.png" alt="Github">
                    </a>
                </li>
            </ul>

        </footer>
    </div>
</div>


<!-- Boostrap js link -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js"
        integrity="sha384-G/EV+4j2dNv+tEPo3++6LCgdCROaejBqfUeNjuKAiuXbjrxilcCdDz6ZAVfHWe1Y"
        crossorigin="anonymous"></script>

<!-- Custom JS link -->
<script src="js/main.js"></script>
<script src="js/project.js"></script>

</body>
</html>