<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>sujons.com</title>
    <!-- Montserrat font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
    <!-- Roboto font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
    <!-- Bootstrap link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/about.css" rel="stylesheet">
    <link href="css/project.css" rel="stylesheet">
</head>


<body>

<!-- Nav -->
<nav class="navbar navbar-expand-lg bg-body-tertiary custom-navbar">
    <div class="container">
        <a class="navbar-brand custom-brand" href="index.php">
            <div class="split-text-container">
                <span class="text-part left">Su</span>
                <span class="text-part right">Jon</span>
            </div>
        </a>
        <button class="navbar-toggler custom-navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                aria-label="Toggle navigation">
            <img class="custom-navbar-toggler menu-icon" src="./assets/home/icon/hamburger-menu.png" alt="menu-bar">
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                <a class="nav-link" href="index.php" title="Home">Home</a>
                <a class="nav-link" href="about.php" title="About Me">About</a>
                <a class="nav-link" href="index.php#section-2" title="My Skills">Skills</a>
                <a class="nav-link" href="projects.php" title="View My Projects">Projects</a>
                <a class="nav-link" href="assets/home/Abdur_Sujon_CV_Web_Version.pdf" target="_blank" title="View My CV">CV</a>
                <div class="d-flex flex-row justify-content-start">
                    <a class="nav-link contact-link" href="mailto:abdur.sujon.dev@gmail.com" title="Email Me">
                        <img src="assets/home/icon/email.png" alt="email">
                    </a>
                    <a class="nav-link contact-link" href="https://www.linkedin.com/in/abdursujon/"
                       title="View My LinkedIn">
                        <img src="assets/home/icon/linkedin.png" alt="linkedin">
                    </a>
                    <a class="nav-link contact-link" href="https://github.com/abdursujon" title="View My Github">
                        <img src="assets/home/icon/github.png" alt="github">
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>

<main>